apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnet-people-api
spec:
  selector:
      matchLabels:
        app: aspnet-people-api
  replicas: 1
  template:
      metadata:
        labels:
            app: aspnet-people-api
      spec:
        containers:
        - name: aspnet-people-api-pod
          image: dawborycki/people:{{BUILD_NUMBER}}          
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: aspnet-people-api-svc  
spec:
  selector:
    app: aspnet-people-api
  type: NodePort
  ports:
  - port: 80
